apiVersion: apps/v1
kind: Deployment
metadata:
  name: salesreport-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
      - name: your-app-container
        image: kalomika11/sales110716:latest
        ports:
          - containerPort: 3000
        env:
         - name: MONGODB_URI
           value: "mongodb://sales110716:27017/sales"
      - name: sales110716
        image: mongo:latest
        ports:
           - containerPort: 27017